/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hth_autoselfdrivingdrone_MainActivity */

#ifndef _Included_com_hth_autoselfdrivingdrone_MainActivity
#define _Included_com_hth_autoselfdrivingdrone_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_hth_autoselfdrivingdrone_MainActivity_REQUEST_PERMISSION_CODE
#define com_hth_autoselfdrivingdrone_MainActivity_REQUEST_PERMISSION_CODE 12345L
#undef com_hth_autoselfdrivingdrone_MainActivity_PERMISSIONS_REQUEST_CODE
#define com_hth_autoselfdrivingdrone_MainActivity_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_hth_autoselfdrivingdrone_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_tistory_webnautes_useopencvwithndk_1build_MainActivity_ConvertRGBtoGray
        (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
